[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdf2d = {path = "../sdf2d"}
image = "0.24"
glam = "0.20"